# Generated by Django 5.1 on 2024-08-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredient_created_at_ingredient_unit_and_more'),
        ('recipe', '0006_remove_recipe_created_at_remove_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_set', to='recipe.recipe'),
        ),
    ]
