# Generated by Django 5.1 on 2024-08-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_remove_ingredient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, default='unit', max_length=50, null=True),
        ),
    ]
