# Generated by Django 5.1 on 2024-08-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
